-- Table: "LOCADORA PASSATEMPO"."ALUGUEL"

-- DROP TABLE "LOCADORA PASSATEMPO"."ALUGUEL";

CREATE TABLE "LOCADORA PASSATEMPO"."ALUGUEL"
(
  "ID_ALUGUEL" integer NOT NULL,
  "ID_ITEM" integer NOT NULL,
  "ID_PRAZO" integer NOT NULL,
  "ID_PAGAMENTO" integer NOT NULL,
  "VALOR_ALUGUEL" integer NOT NULL,
  "DESCONTO" integer NOT NULL,
  "DATA_DEVOLUCAO" date NOT NULL,
  "PAGAMENTO" integer NOT NULL,
  "LANCAMENTO" character(1) NOT NULL,
  CONSTRAINT "ID_ALUGUEL PK" PRIMARY KEY ("ID_ALUGUEL"),
  CONSTRAINT "ID_ITEM FK" FOREIGN KEY ("ID_ITEM")
      REFERENCES "LOCADORA PASSATEMPO"."ITEM" ("ID_ITEM") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "ID_PAGAMENTO FK" FOREIGN KEY ("ID_PAGAMENTO")
      REFERENCES "LOCADORA PASSATEMPO"."PAGAMENTOS" ("ID_PAGAMENTO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "ID_PRAZO FK" FOREIGN KEY ("ID_PRAZO")
      REFERENCES "LOCADORA PASSATEMPO"."PRAZO" ("ID_PRAZO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "LOCADORA PASSATEMPO"."ALUGUEL"
  OWNER TO postgres;

-- Index: "LOCADORA PASSATEMPO"."fki_ID_ITEM FK"

-- DROP INDEX "LOCADORA PASSATEMPO"."fki_ID_ITEM FK";

CREATE INDEX "fki_ID_ITEM FK"
  ON "LOCADORA PASSATEMPO"."ALUGUEL"
  USING btree
  ("ID_ITEM");

-- Index: "LOCADORA PASSATEMPO"."fki_ID_PAGAMENTO FK"

-- DROP INDEX "LOCADORA PASSATEMPO"."fki_ID_PAGAMENTO FK";

CREATE INDEX "fki_ID_PAGAMENTO FK"
  ON "LOCADORA PASSATEMPO"."ALUGUEL"
  USING btree
  ("ID_PAGAMENTO");

-- Index: "LOCADORA PASSATEMPO"."fki_ID_PRAZO FK"

-- DROP INDEX "LOCADORA PASSATEMPO"."fki_ID_PRAZO FK";

CREATE INDEX "fki_ID_PRAZO FK"
  ON "LOCADORA PASSATEMPO"."ALUGUEL"
  USING btree
  ("ID_PRAZO");

